### PR TITLE
Update release-image.yaml

### PR DESCRIPTION
**Pull request by Mahima-Gaikwad**
Updated ko command to build multi-arch images

### CODE REVIEW

**Comment by mgencur** [comment]
@pierDipi Hi! The multiarch image is required for testing on IBM Power/Z. Canyou merge this please? The github action should then automatically build it as multiarch.

**Review by pierDipi — APPROVED** [review]
LGTM

**Comment by pierDipi** [comment]
Image published: https://github.com/pierDipi/sacura/pkgs/container/sacura%2Fsacura-7befbbbc92911c6727467cfbf23af88f/108485927?tag=latest

**Comment by mgencur** [comment]
Nice!

**Pull request merged**
